version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/appengine-spring-boot-plugin
    steps:
      - run:
          name: Install
          command: |
            apk --update add openjdk8
            gcloud components install app-engine-java
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run:
          name: Build
          command: |
            ./gradlew build

      - run:
          name: Collect
          command: |
            cp -av */build/test-results/test/*.xml build/test-results/test
      - store_test_results:
          path: build/test-results/test

      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - deploy:
          name: Publish
          command: |
            if [ "$CIRCLE_TAG" ]; then
              ./gradlew publishPlugins -Pgradle.publish.key="$GRADLE_PUBLISH_KEY" -Pgradle.publish.secret="$GRADLE_PUBLISH_SECRET"
            fi

deployment:
  publish:
    tag: /.*/
